---

- name: Validate freeipa vars
  ansible.builtin.assert:
    that:
      - keycloak_ldap_connection is string and keycloak_ldap_connection | length > 0
      - keycloak_ldap_suffix is string and keycloak_ldap_suffix | length > 0
      - keycloak_ldap_bind_password is string and keycloak_ldap_bind_password | length > 0
    fail_msg: "FreeIPA enabled but required variables are missing/empty."
  changed_when: false

- name: Ensure FreeIPA realm exists
  when: keycloak_freeipa
  community.general.keycloak_realm:
    validate_certs: "{{ keycloak_validate_certs }}"
    auth_client_id: "{{ keycloak_client_id }}"
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: "{{ keycloak_auth_realm }}"
    auth_username: "{{ keycloak_auth_user }}"
    auth_password: "{{ keycloak_auth_password }}"
    id: freeipa
    realm: freeipa
    state: present

- name: Include FreeIPA realm
  ansible.builtin.include_tasks: "freeipa_ldap.yml"
  when: keycloak_ldap
