---

- name: Wait for Keycloak to be up
  uri:
    url: "{{ keycloak_url }}/realms/master"
    method: GET
    status_code: 200
    validate_certs: "{{ keycloak_validate_certs }}"
  register: keycloak_up
  retries: 10
  delay: 6
  until: keycloak_up.status == 200

- name: Ensure FreeIPA realm exists
  when: keycloak_freeipa
  community.general.keycloak_realm:
    validate_certs: "{{ keycloak_validate_certs }}"
    auth_client_id: "{{ keycloak_client_id }}"
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: "{{ keycloak_auth_realm }}"
    auth_username: "{{ keycloak_auth_user }}"
    auth_password: "{{ keycloak_auth_password }}"
    id: freeipa
    realm: freeipa
    state: present
  register: freeipa_realm_result
  retries: 5
  delay: 3
  until: freeipa_realm_result is succeeded

- name: Include FreeIPA realm
  ansible.builtin.include_tasks: "freeipa_ldap.yml"
  when: keycloak_ldap
