---
# SPDX-License-Identifier: MIT-0
namespace: fossgalaxy
name: selfhosted
version: 0.1.0
readme: README.md
authors:
  - Joseph Walton-Rivers <webpigeon@fossgalaxy.com>

description: Composable Ansible roles for running self-hosted services using Podman and systemd quadlets.

license:
  - GPL-3.0-or-later
tags:
  - linux

dependencies:
  "fossgalaxy.infra": "0.1.0"

# Metadata
repository: https://github.com/fossgalaxy/collection-selfhosted/
homepage: https://www.fossgalaxy.com
issues: https://github.com/fossgalaxy/collection-selfhosted/issues
