---

- name: Validate container engine
  ansible.builtin.assert:
    that:
      - taskchampion_container_engine in ['podman']
    fail_msg: "Unsupported container engine: {{ taskchampion_container_engine }}"
  changed_when: false

- name: Include container engine tasks
  ansible.builtin.include_tasks: "engine_{{ taskchampion_container_engine }}.yml"
